import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "../components/Navbar";
import { Footer } from "../components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Anime Wiki",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="justify-center flex pb-10">
          <div className="w-full max-w-[72rem] flex flex-col gap-20 justify-center px-5">
            <Navbar />
            <div className="justify-center flex">{children}</div>
            <Footer />
          </div>
        </main>
      </body>
    </html>
  );
}
